version: "3.9"

services:
  db:
    image: postgres:15
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=angle_dev
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5455:5432"

  # web:
  #   build: .
  #   restart: always
  #   environment:
  #     - DATABASE_URL=ecto://postgres:postgres@db:5432/angle_dev
  #     - PORT=4000
  #   volumes:
  #     - .:/app
  #   ports:
  #     - "4000:4000"
  #   depends_on:
  #     - db

volumes:
  postgres_data:
